version: '3.0'
services:
  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - MODE=DEV
      - ROOT_URL=http://localhost:5000
    entrypoint: 
      - bash
      - -c 
    command: > 
      "python3 index.py"
      
  db:
    image: postgres:13-alpine
    volumes:
      - .postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5405:5432
    restart: always